### ISSUE TITLE
Please use cb form of writeStream.end()

### ISSUE THREAD

**Issue by Nedgeva** [zulhilmizainuddin/multipart-download#2]
Hello! I found your lib is very useful, but faced some little bugs.
First use callback form of calling writeStream.end() in ../src/models/multipart-download.d.ts (.js), it's reducing a lot errors caused by async behaviour when using this lib heavily. 
So, instead emitting 'end' event right after, you should call this in end method callback:
```
new partial_download_1.default()
...
.on('end', () => {
  if (options.saveDirectory) {
    writeStream.end(() => {
      // do the job here
      if (++endCounter === options.numOfConnections) {
        this.emit('end', filePath);
      }
    });
  }
 });
```

I know, i should PR this, but i'm very lazy to mess with typescript, lol.

**Comment by Nedgeva** [comment]
Hi! This fix only solves problem when you need completely downloaded file right after "multipart-download" emitted 'end' event. 

There is some another problem with locking downloaded file (under Win 10), but i'm not sure whether it's because of lib or node's 'fs' module itself. I think I'll explain this problem in more detailed way as another issue.

**Comment by zulhilmizainuddin** [comment]
I've published a new version to npmjs to emit the end event in the writeStream.end() callback.

**Comment by Nedgeva** [comment]
Great! Thanks.
