### ISSUE TITLE
Lockfile: multipart-download do not releases file after download

### ISSUE THREAD

**Issue by Nedgeva** [zulhilmizainuddin/multipart-download#3]
I'm using "multipart-download" in a complex scenario, where downloaded file should be streamed as http response and then removed (offtopic: it's would be great if this lib could expose option to write into Buffer, not only to filesystem), but there is problem - downloaded file can't be released and available for erasing only when node process shuts down.

Following sample of code shows that file can't be removed once it's have been completely downloaded, at least on Windows 10 x64 2015 LTSB.
```javascript 
const MultipartDownload = require('multipart-download')
const fs = require('graceful-fs')

const removeFile = filePath => {
  console.log('remove file called')
  fs.unlink(filePath, err => {
    if (err)
      return console.error(err)
  })
}

new MultipartDownload()
  .start('... any direct file url goes there ...', {
    numOfConnections: 5,
    saveDirectory: process.cwd(),
    fileName: 'file.bin'
  })
  .on('end', (filePath) => {
    console.log(`Downloaded file path: ${filePath}`)
    setTimeout(() => { /* just to keep node running for 1 min */ }, 60000)
    // Locked! File actually is only marked for removal, and will be really erased once node process stops
    setTimeout(() => removeFile(filePath), 100)
  })
```
Note that there is no difference between 'fs' and 'graceful-fs' modules (even if i replace all fs-require sections inside 'multipart-download' lib), problem still exists.
I'm solved this partially using 'cluster' module and running 'multipart-download' as a separate process.
Probably related to same problems in different modules: [Multi-threaded-downloader #187 issue](https://github.com/tusharmath/Multi-threaded-downloader/issues/187)

**Comment by zulhilmizainuddin** [comment]
As stated by @Nedgeva, this looks like an existing issue with the `fs` module in `Windows`. Keeping this open for reference.
