### ISSUE TITLE
Emit error events instead of throwing exceptions

### ISSUE THREAD

**Issue by Nedgeva** [zulhilmizainuddin/multipart-download#4]
'MultipartDownload' class is inherited from and extends the 'EventEmitter' class, so it should emit 'error' events in case of app fail.
Try/catch statement in JS can't intercept async errors and throwing exceptions is pretty useless.
For example error in [multipart-download.ts#L68](https://github.com/zulhilmizainuddin/multipart-download/blob/ca78fc1abfa9037b5634ca2d0f5d2fe15ffd4d4e/src/models/multipart-download.ts#L68) will never be handled, as network request was processed asynchronously, This one can be easily reproduced and tested if your dev server doesn't return 'accept-ranges' header.
I think it's good idea to swap all `throw` statements with `this.emit('error', errMsg)`...

**Comment by zulhilmizainuddin** [comment]
Thanks for pointing out this oversight.

I do agree that since `MultipartDownload` is an `EventEmitter`, it should implement the `EventEmitter` interface by emitting errors instead of throwing them.

I will look into making the changes.

**Comment by zulhilmizainuddin** [comment]
Error emitted instead of thrown in latest npm package
