### ISSUE TITLE
request.head return undefined and app crashed

### ISSUE THREAD

**Issue by nguyentuandat** [zulhilmizainuddin/multipart-download#9]
Thank you for your awesome package.

When i try to download a mp4 file, It had an error when try to send a `HEAD` request to url. Then app crashed.
The root cause is on 
[src/models/partial-request-query.ts#L22-L23](https://github.com/zulhilmizainuddin/multipart-download/blob/master/src/models/partial-request-query.ts#L22-L23)
``` typescript                   
acceptRanges: res.headers['accept-ranges'],
contentLength: parseInt(res.headers['content-length'])
```
In this case, `res is undefined`.

Can you fix this?

**Comment by zulhilmizainuddin** [comment]
Hi, please try latest version `1.2.0`.

I have updated it to `return` on error
https://github.com/zulhilmizainuddin/multipart-download/blob/master/src/models/partial-request-query.ts#L18

**Comment by nguyentuandat** [comment]
Thank you ☺️
